### ISSUE TITLE
Lena zum Maintainer machen

### ISSUE THREAD

**Issue by Lena-Luise** [DH-BUW/Webentwicklung2021#1]
@StephanMa 

Würdest du mich zu maintainer machen bitte? Danke :-)

**Comment by StephanMa** [comment]
Solltest du bereits schon sein... sagt mir Github..

**Comment by Lena-Luise** [comment]
@StephanMa 

Finde den Fehler ;-)

![grafik](https://user-images.githubusercontent.com/11693075/139651407-9265a469-af35-4a1c-8733-13b2922d7605.png)

**Comment by StephanMa** [comment]
Finde den Fehler

![image](https://user-images.githubusercontent.com/6735556/139651547-d83154f7-3335-412a-aa5f-2275140c63be.png)

**Comment by Lena-Luise** [comment]
Ja aber das ändert ja nix an der obigen Sache oder?

**Comment by StephanMa** [comment]
Eigentlich sollten die Berechtigungen gezogen werden. Darfst du denn nix?

**Comment by Lena-Luise** [comment]
![grafik](https://user-images.githubusercontent.com/11693075/139651941-5747344a-e219-4912-9efd-9dde69e14c72.png)

**Comment by Lena-Luise** [comment]
Nope!

**Comment by StephanMa** [comment]
Das ist aber Äpfeln mit Birnen vergleichen...
HIER sind wir im Repo Webentwicklung. Dein Screenshot ist aber von der Gruppe DH-BUW...
;) Du willst also Maintain in  DH-BUW?
kommt

**Comment by Lena-Luise** [comment]
Ich kann aber auch im Repo Webentwicklung nichts tun, also zB keine Leute einladen. Das haben wir am Freitag fetsgestellt. Und da das Repo Webentwicklung zur Gruppe DH-BUW gehört, dachte ich, daran hängts.

**Comment by StephanMa** [comment]
Versuch mal bitte...

**Comment by Lena-Luise** [comment]
Jetzt gehts glaub ich 

![grafik](https://user-images.githubusercontent.com/11693075/139652498-662e5207-1626-4de8-a412-ab2d6d395952.png)

**Comment by StephanMa** [comment]
Sehr gut

**Comment by Lena-Luise** [comment]
Bzw. im Repo Webentwicklung: 

![grafik](https://user-images.githubusercontent.com/11693075/139652686-addd282c-0add-4838-af0e-889ed03f1766.png)

**Comment by Lena-Luise** [comment]
Und das auf der Projektebene

![grafik](https://user-images.githubusercontent.com/11693075/139652869-691b07ab-5fe4-413a-bb4b-013fe628e003.png)
